version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ainstein_prm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=your_db_password
      - DB_NAME=ainstein_prm
      - JWT_SECRET=your_jwt_secret_key_here
      - GEMINI_API_KEY=your_gemini_api_key_here
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
