services:
  database:
    image: postgres:15
    container_name: prm-database
    environment:
      POSTGRES_DB: prm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prm-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prm-backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: prm_db
      JWT_SECRET: ${JWT_SECRET:-your-default-jwt-secret-change-this}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:-}
      STRIPE_PRICE_ID_BASIC: ${STRIPE_PRICE_ID_BASIC:-price_basic_default}
      STRIPE_PRICE_ID_PREMIUM: ${STRIPE_PRICE_ID_PREMIUM:-price_premium_default}
      STRIPE_PRICE_ID_ENTERPRISE: ${STRIPE_PRICE_ID_ENTERPRISE:-price_enterprise_default}
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - prm-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: prm-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - prm-network

volumes:
  postgres_data:

networks:
  prm-network:
    driver: bridge
