version: '3.8'

services:
  database:
    image: postgres:15
    container_name: prm-database
    environment:
      POSTGRES_DB: prm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prm-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prm-backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: prm_db
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - prm-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: prm-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - prm-network

volumes:
  postgres_data:

networks:
  prm-network:
    driver: bridge
